name: Build and release SoftCOM

# on:
#   push:
#     tags:
#       - '*'
#     branches:
#       - main
on: [push]
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine build
      - name: Build project
        run: |
          python -m build
      - uses: actions/checkout@v2
      - name: Upload wheel to release
        uses: actions/upload-release-asset@v1
        with:
          release_id: ${{ github.event.release.id }}
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist/*.whl
          asset_name: ${{ github.event.release.name }}.whl
          asset_content_type: application/python-wheels
